// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPe7C8S8g_rA2IO-aHawS79hqhxQQqbM',
    appId: '1:750683169731:web:47bb651e3e3e4f108b5376',
    messagingSenderId: '750683169731',
    projectId: 'junk-food-50a33',
    authDomain: 'junk-food-50a33.firebaseapp.com',
    storageBucket: 'junk-food-50a33.appspot.com',
    measurementId: 'G-94778NWHBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgH18tT-GvFWzMsoRwi6tnYhFsC-vnO60',
    appId: '1:750683169731:android:e0feab0e4db2274b8b5376',
    messagingSenderId: '750683169731',
    projectId: 'junk-food-50a33',
    storageBucket: 'junk-food-50a33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM_1j1BUsCWLw2rkg7NjRWfbPaD4Qa6ik',
    appId: '1:750683169731:ios:ebc52f5526329d328b5376',
    messagingSenderId: '750683169731',
    projectId: 'junk-food-50a33',
    storageBucket: 'junk-food-50a33.appspot.com',
    iosClientId: '750683169731-jk94e4qa6j5kl9e90ci0jtnv8th06n9h.apps.googleusercontent.com',
    iosBundleId: 'com.junkfood.junkFood',
  );
}
